### ISSUE TITLE
I can't be sure if a URL was successfully oEmbedded 

### ISSUE THREAD

**Issue by Tomtomgo** [Urigo/angular-embedly#16]
Assuming oEmbed is a verb, I can never know if the URL to be oEmbedded is actually oEmbedded.

For example retrieving [this URL](http://hbr.org/video/2228473586001/connect-with-any-audience) ([verify on Embed.ly](http://embed.ly/docs/explore/oembed?url=http%3A%2F%2Fhbr.org%2Fvideo%2F2228473586001%2Fconnect-with-any-audience)) doesn't throw an error, but also doesn't return an embed code. The user of the page then doesn't see anything.

We could find this out by looking at the result of the oEmbed call and see that it doesn't contain a HTML entry:

``` yaml
description: "Nancy Duarte, CEO of Duarte, Inc., outlines best practices for preparing your next speech."
provider_name: "Hbr"
provider_url: "http://hbr.org"
thumbnail_height: 720
thumbnail_url: "http://brightcove.vo.llnwd.net/e1/pd/2071817190001/2071817190001_2228601438001_stillImage-1-49cu0ygy-2235560989001.jpg?pubId=2071817190001"
thumbnail_width: 1280
title: "Connect with Any Audience"
type: "link"
url: "http://hbr.org/video/2228473586001/connect-with-any-audience"
version: "1.0"
```
### Suggestion

My suggestion would be to add an attribute to the directive that passes a function to be called in this situation. That might look something like this:

``` html
<em-embed urlsearch="{{url}}" onerror="saySorryToUser()"></em-embed>
```

So, I can build it, with proper commit messages and all. If you have any comments let me know!
